import io
import zipfile

from extractors.peel_docx_metadata import extract_docx_metadata
from services.peel_draft_sync_service import _merge_auto_fields, build_auto_form_data


def docx_bytes(body_xml: str) -> bytes:
    document = f'''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
    <w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
      <w:body>{body_xml}</w:body>
    </w:document>'''
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w") as archive:
        archive.writestr("word/document.xml", document)
    return buffer.getvalue()


def test_metadata_extraction_preserves_values_split_across_runs_and_tables():
    content = docx_bytes('''
      <w:p><w:r><w:t>Production Order </w:t></w:r><w:r><w:t>No.:  70001234</w:t></w:r></w:p>
      <w:tbl><w:tr><w:tc><w:p><w:r><w:t>Cell Vendor:</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>LONGi Solar</w:t></w:r></w:p></w:tc></w:tr></w:tbl>
      <w:p><w:r><w:t>Wp - 640 Wp</w:t></w:r></w:p>
    ''')
    assert extract_docx_metadata(content) == {
        "po_number": "70001234",
        "cell_vendor": "LONGi Solar",
        "wp": "640 Wp",
    }


def test_metadata_extraction_returns_nulls_when_labels_are_missing():
    assert extract_docx_metadata(docx_bytes("<w:p><w:r><w:t>Unrelated document</w:t></w:r></w:p>")) == {
        "po_number": None, "cell_vendor": None, "wp": None,
    }


def test_automatic_form_contains_all_metadata_and_readings_exactly():
    record = {
        "date": "2026-07-20", "shift": "A", "Stringer": 1, "Unit": "A",
        "po_number": "7000 1234", "cell_vendor": "Vendor  Name", "wp": "640Wp",
        "Front_1_1": 1.25, "Back_16_7": 1.5,
    }
    form = build_auto_form_data("2026-07-20", "A", "FAB-II Line-I", [record])
    assert form["row_0_cell_4"] == "7000 1234"
    assert form["row_0_cell_5"] == "Vendor  Name"
    assert form["wp"] == "640Wp"
    assert form["row_0_cell_6"] == "1.25"
    assert form["row_0_cell_229"] == "1.5"


def test_draft_resynchronization_replaces_only_previous_auto_fields():
    existing = {
        "row_0_cell_4": "old-po", "row_0_cell_6": "old-reading",
        "operatorRemark": "keep me", "preparedBySignature": "Operator One",
        "autoGeneratedFields": ["row_0_cell_4", "row_0_cell_6"],
    }
    merged = _merge_auto_fields(existing, {"row_0_cell_4": "new-po"})
    assert merged["row_0_cell_4"] == "new-po"
    assert "row_0_cell_6" not in merged
    assert merged["operatorRemark"] == "keep me"
    assert merged["preparedBySignature"] == "Operator One"
