"""Idempotently synchronize extracted peel records into the existing report workflow."""

import hashlib
import json
import logging
from datetime import datetime, timezone
from typing import Any, Dict, Iterable, List

from pymongo import ASCENDING
from pymongo.errors import DuplicateKeyError

from models.peel_data_models import peel_data_collection
from models.peel_test_models import PeelTestReport, ensure_peel_test_indexes, peel_test_collection
from mongo_indexes import ensure_index


logger = logging.getLogger(__name__)
REPORT_TYPE = "solar-cell-peel-strength"
LINES = {"FAB-II Line-I": range(1, 7), "FAB-II Line-II": range(7, 13)}


def _timestamp() -> str:
    return datetime.now(timezone.utc).isoformat()


def _measurement(record: Dict[str, Any], side: str, position: int, ribbon: int) -> Any:
    direct = record.get(f"{side}_{position}_{ribbon}")
    if direct not in (None, ""):
        return direct
    for item in record.get("sample_results") or []:
        if str(item.get("side", "")).lower() == side.lower() and item.get("bus_pad_position") == position and item.get("ribbon") == ribbon:
            return item.get("value")
    return None


def _value(record: Dict[str, Any], *keys: str) -> str:
    for key in keys:
        value = record.get(key)
        if value not in (None, "", "UNKNOWN"):
            return str(value)
    return ""


def build_auto_form_data(date: str, shift: str, line: str, records: Iterable[Dict[str, Any]]) -> Dict[str, str]:
    form: Dict[str, str] = {"selectedDate": date, "selectedShift": shift, "selectedLine": line}
    sorted_records = sorted(records, key=lambda item: (int(item.get("Stringer", item.get("stringer", 0)) or 0), str(item.get("Unit", item.get("unit", "")))))
    for row, record in enumerate(sorted_records[:12]):
        form[f"row_{row}_cell_0"] = _value(record, "date", "Date")
        form[f"row_{row}_cell_1"] = _value(record, "shift", "Shift")
        form[f"row_{row}_cell_2"] = _value(record, "Stringer", "stringer")
        form[f"row_{row}_cell_3"] = _value(record, "Unit", "unit")
        form[f"row_{row}_cell_4"] = _value(record, "po_number", "PO")
        form[f"row_{row}_cell_5"] = _value(record, "cell_vendor", "Cell_Vendor")
        for side, start in (("Front", 6), ("Back", 118)):
            for position in range(1, 17):
                for ribbon in range(1, 8):
                    value = _measurement(record, side, position, ribbon)
                    if value not in (None, ""):
                        cell = start + (position - 1) * 7 + ribbon - 1
                        form[f"row_{row}_cell_{cell}"] = str(value)
    first = sorted_records[0] if sorted_records else {}
    form["wp"] = _value(first, "wp", "Wp", "WP")
    return form


def _merge_auto_fields(existing: Dict[str, Any], generated: Dict[str, str]) -> Dict[str, Any]:
    merged = dict(existing)
    for key in existing.get("autoGeneratedFields") or []:
        merged.pop(key, None)
    merged.update(generated)
    merged["autoGeneratedFields"] = sorted(generated)
    return merged


def _averages(form: Dict[str, Any]) -> Dict[str, str]:
    result: Dict[str, str] = {}
    for row in range(12):
        for side, start, prefix in (("Front", 6, "front"), ("Back", 118, "back")):
            for position in range(1, 17):
                values = []
                for offset in range(7):
                    try:
                        values.append(float(form.get(f"row_{row}_cell_{start + (position - 1) * 7 + offset}")))
                    except (TypeError, ValueError):
                        pass
                result[f"{prefix}_avg_{row}_{position}"] = f"{sum(values) / len(values):.2f}" if values else "0.00"
    return result


def _report_name(date: str, shift: str, line: str) -> str:
    parsed = datetime.strptime(date, "%Y-%m-%d")
    safe_line = "_".join(part for part in line.replace("-", " ").split() if part)
    return f"Peel_Test_Report_{parsed.day}_{parsed.strftime('%b')}_{parsed.year}_Shift_{shift}_{safe_line}"


def synchronize_peel_drafts(date: str, shift: str) -> Dict[str, int]:
    ensure_peel_test_indexes()
    ensure_index(peel_test_collection, [("automationKey", ASCENDING)], unique=True, sparse=True, name="unique_peel_automation_key")
    records = list(peel_data_collection.find({"date": date, "shift": shift}))
    summary = {"created": 0, "updated": 0, "submitted_skipped": 0, "empty_skipped": 0}
    for line, stringers in LINES.items():
        line_records = []
        for record in records:
            try:
                if int(record.get("Stringer", record.get("stringer"))) in stringers:
                    line_records.append(record)
            except (TypeError, ValueError):
                continue
        if not line_records:
            summary["empty_skipped"] += 1
            continue
        automation_key = f"{REPORT_TYPE}|{date}|{shift}|{line}".lower()
        query = {"date": date, "shift": shift, "line": line}
        finalized = peel_test_collection.find_one({**query, "$or": [
            {"workflowState": {"$in": ["submitted", "approved"]}},
            {"status": {"$in": ["submitted", "approved"]}},
            {"workflowState": {"$exists": False}},
        ]})
        if finalized:
            summary["submitted_skipped"] += 1
            logger.info("submitted_report_skipped date=%s shift=%s line=%s report_id=%s", date, shift, line, finalized.get("_id"))
            continue
        existing = peel_test_collection.find_one({"$and": [
            {"$or": [{"automationKey": automation_key}, query]},
            {"workflowState": {"$nin": ["submitted", "approved"]}},
            {"status": {"$nin": ["submitted", "approved"]}},
        ]})
        generated = build_auto_form_data(date, shift, line, line_records)
        fingerprint = hashlib.sha256(json.dumps(generated, sort_keys=True).encode()).hexdigest()
        if existing and existing.get("extractionFingerprint") == fingerprint:
            continue
        if existing:
            sync_claim = peel_test_collection.update_one(
                {
                    "_id": existing["_id"],
                    "workflowState": {"$nin": ["submitted", "approved"]},
                    "status": {"$nin": ["submitted", "approved"]},
                    "submissionInProgress": {"$ne": True},
                    "automationSyncing": {"$ne": True},
                },
                {"$set": {"automationSyncing": True}},
            )
            if not sync_claim.modified_count:
                logger.info("draft_sync_skipped_busy date=%s shift=%s line=%s", date, shift, line)
                continue
        old_payload = PeelTestReport.from_dict(existing).get_data() if existing and existing.get("s3_key") else {}
        form = _merge_auto_fields(old_payload.get("form_data", {}), generated)
        averages = _averages(form)
        now = _timestamp()
        metadata = {
            "name": existing.get("name") if existing else _report_name(date, shift, line),
            "timestamp": existing.get("timestamp") if existing else now,
            "date": date, "shift": shift, "line": line,
            "lineNumber": "I" if line.endswith("Line-I") else "II",
            "productionOrderNo": _value(line_records[0], "po_number", "PO"),
            "wp": generated.get("wp") or None,
            "status": "draft", "workflowState": "draft", "reportType": REPORT_TYPE,
            "automationKey": automation_key, "autoGenerated": True,
            "extractionFingerprint": fingerprint, "updatedAt": now,
            "isSigned": False,
        }
        if existing:
            try:
                report = PeelTestReport.from_dict(existing)
                if not report.save_data(form, old_payload.get("row_data", []), averages):
                    raise RuntimeError(f"Failed to update automatic Peel draft payload {existing['_id']}")
                result = peel_test_collection.update_one(
                    {"_id": existing["_id"], "automationSyncing": True},
                    {"$set": metadata, "$unset": {"automationSyncing": ""}},
                )
                if result.modified_count:
                    summary["updated"] += 1
                    logger.info("draft_updated date=%s shift=%s line=%s report_id=%s", date, shift, line, existing.get("_id"))
            finally:
                peel_test_collection.update_one({"_id": existing["_id"]}, {"$unset": {"automationSyncing": ""}})
            continue
        try:
            inserted = peel_test_collection.insert_one({**metadata, "s3_key": ""})
        except DuplicateKeyError:
            # A concurrent extractor won the automation key; the next run compares fingerprints.
            continue
        try:
            report = PeelTestReport.create_from_data(metadata["name"], metadata["timestamp"], str(inserted.inserted_id), form, [], averages)
            peel_test_collection.update_one({"_id": inserted.inserted_id}, {"$set": {"s3_key": report.s3_key}})
        except Exception:
            peel_test_collection.delete_one({"_id": inserted.inserted_id, "s3_key": ""})
            raise
        summary["created"] += 1
        logger.info("draft_created date=%s shift=%s line=%s report_id=%s", date, shift, line, inserted.inserted_id)
    return summary
